### ISSUE TITLE
Monaco editor version

### ISSUE THREAD

**Issue by cintaccs** [vanillawc/wc-monaco-editor#10]
Hi,
Any special reason not using the latest version 20.0 of the Monaco editor?

**Comment by evanplaice** [comment]
Nope, just need to rebuild the ESM distribution of Monaco Editor. I'll bump it to 20.x as soon as I finish adding these new opions.

**Comment by cintaccs** [comment]
> Nope, just need to rebuild the ESM distribution of Monaco Editor. I'll bump it to 20.x as soon as I finish adding these new opions.

Thanks a lot! sounds good! I am currently having a kind of similar WC with lit-element using Monaco - (20.0) - but had to use slots and a lot of pre and post cleanup... Looking forward to find potentially a solid 1 component solution. You seems to have got a long way to that! (I ran into issues when combining Monaco with shadow DOM basically...).

**Comment by evanplaice** [comment]
I'm a little familiar w/ lit-element. I think you can opt-out of shadowDOM and use lightDOM instead, check out [this article](https://medium.com/lightbaseio/bootstrap-4-lit-element-37c857a6bcca).

But yeah. Lots of devs say standard web components are more complex (ie they're not). With the standard approach switching between shadowDOM and lightDOM is relatively easy. I ran into the same issue w/ shadowDOM, Monaco Editor is definitely not shadowDOM friendly.

The hardest part about building this was getting Monaco built into something that works with spec ESM. The ESM that Monaco-Editor works w/ Webpack but it's *not* spec ESM. I ended up disabling code splitting (ie breaks w/ CORS) and bundling each module into a single source file. It's not the most efficient strategy but neither is using Webpack. Ironically, this component doesn't work w/ Webpack b/c webpack still hasn't added support for the `import.meta` proposal.

Anyway, this is most definitely a 1 component solution that just works. There is no magic, no bundlers, no extra steps. Alternatively, if you need a code editor that is a LOT smaller I recommend checking out the [wc-codemirror](https://github.com/vanillawc/wc-codemirror) project. Same concept (ie abstract away all the complexity), different editor.

**Comment by evanplaice** [comment]
Monaco is upgraded to v20 in [v1.10.1](https://github.com/vanillawc/wc-monaco-editor/releases/tag/v1.10.1)

Any other requests before I close this issue?

**Comment by cintaccs** [comment]
Thanks a lot! Very quick!! :-)
I have a similar experience with Webpack and building Monaco editor - I am not sure I understand why Monaco team doesn't seems to care for simple/easy bundling... I have a working solution however - with one remaining obstacle regarding the codicon TTF file that I simply can't get into the same folder as the generated workers...

Here is my current webpack FYI:

```const webpack = require('webpack');
const path = require('path');
const TerserPlugin = require("terser-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const OptimizeCssAssetsPlugin = require("optimize-css-assets-webpack-plugin");


module.exports = {
	mode: 'production',
	entry: {
		"DynamicAI_Editor": './src/DynamicAI_Editor/main.js',
		"editor.worker": 'monaco-editor/esm/vs/editor/editor.worker.js',
		"json.worker": 'monaco-editor/esm/vs/language/json/json.worker',
		"css.worker": 'monaco-editor/esm/vs/language/css/css.worker',
		//"html.worker": 'monaco-editor/esm/vs/language/html/html.worker',
		//"ts.worker": 'monaco-editor/esm/vs/language/typescript/ts.worker',
	},
	optimization: {
		minimizer: [new TerserPlugin({}), new OptimizeCssAssetsPlugin({})],
	},
    plugins: [
        new webpack.optimize.LimitChunkCountPlugin({
          maxChunks: 1,
		}),

		new MiniCssExtractPlugin({
			filename: '[name].css',
			chunkFilename: '[id].css',
		  })

	  ],    
	  

	  
	output: {
		globalObject: 'self',
        filename: '[name].js',
		publicPath: 'monaco/',		
		//publicPath: 'app/monaco/',
		//path: path.resolve(__dirname, '..','app/')
		path: path.resolve(__dirname, '..','app/monaco')
	},
	module: {
		rules: [{
			test: /\.css$/,
			use: [
				
				{
					loader: 'style-loader',
					options: { injectType: 'singletonStyleTag' },
				  },
				  MiniCssExtractPlugin.loader, 'css-loader'	  
				 ]
		}, {
			test: /\.ttf$/,
			use: [
				{
					loader: 'file-loader',
					options: {
					  name: '[name].[ext]',
					  outputPath: '../monaco'					  
					}
				  }							
				]
		}]
	},
};
```

**Comment by cintaccs** [comment]
I agree with you that Monaco (also in my lit-element solution) needs the editor part to be in the LightDOM - and I am using slots to achieve that because the editor is created within a ShadowDOM process. The problem with that is when you get deeper down the components layers - i.e. parent component - child - child ... and need the editor in one of these child components. When the parent of the editor WC is not a LightDOM I can't get it to work (lit element can render into a parent LightDOM - but if there is a ShadowDOM in-between - then I can't figure it out...).
That's at least my experience with it so far.
Thanks for the pointers to wc-codemirror! I am aware of codemirror - on the other hand I think the Monaco = Visual Studio Code - is a strong benefit for Monaco (with the disadvantage of not being for Mobile devices)....

**Comment by cintaccs** [comment]
I am using:
onDidBlurEditorWidget
onDidChangeModelContent
addAction
(with addAction I create entries for the context menu with custom actions) like:
```
                    this.editor.addAction({
                        precondition: null,
                        keybindingContext: null,
                        contextMenuGroupId: action.contextMenuGroupId,
                        contextMenuOrder: action.contextMenuOrder,
                        id: action.id,
                        label: action.label,
                        run: function(ed) {
                            let myvar = action.skeleton;
                            ed.trigger('keyboard', 'type', { text: myvar });
                            return null;
                        }
                    });

```
or
```
                    this.editor.addAction({
                        precondition: null,
                        keybindingContext: null,
                        contextMenuGroupId: action.contextMenuGroupId,
                        contextMenuOrder: action.contextMenuOrder,
                        id: action.id,
                        label: action.label,
                        keybindings: [
                            monaco.KeyMod.CtrlCmd | monaco.KeyCode.F10,
                            monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_K, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_P)
                        ],
                        run: function(ed) {
                            return self.launchStepper(ed);
                        }
                    });

```

on the created editor object - will that work with the wc-monaco-editor implementation?

**Comment by evanplaice** [comment]
Feel free to copy the webpack config from this project. It creates the output you seee in the `monaco/` dir. You can find the webpack config under `.config/monaco.config.js`. I just updated it, incl the `file-loader` setup that copies over the .ttf file. 

Don't ask me why the Monaco devs are importing a font into JS. Seems like a poor decision.

As for your actions. They should work the same for `wc-monaco-editor`. I made the `editor` prop public for that exact reason.

Following feedback from another User, I also exposed a `config` attribute so you can leverage the full range of editor options rather than just the limited set exposed via HTML attributes.

**Comment by cintaccs** [comment]
THanks a lot!!!! (btw - wc-codemirror looks interesting too!! - thanks!)
btw - I am loading my editor with data that are already in memory - i.e. not from a 
```
 src="sample.js"
```
in the component tag.

like:
```
        this.editor = monaco.editor.create(frame, {
            value: this.loading ? 'LOADING....' : this.baseModel.model.fieldValue('editorSrc'),
            language: editorNode.language,.....

```

I think I have run into this issue with wc-monaco-editor previously...  can that be done?

**Comment by cintaccs** [comment]
Thanks a lot Evan!!

**Comment by evanplaice** [comment]
That's what the `value` property is for, to set the editor's contents from JS.

You're welcome :+1:. Web components are still new enough, and there's so much FUD floating around about using web components w/o extra abstracrions (ex lit-html), I'm just happy to see other Devs start to put these projects to use.

**Comment by cintaccs** [comment]
Brilliant! Thanks again! (FYI my reason for using lit-html/lit-element is only partly the component isolation (which is a benefit however) - but mainly because of the template rendering logic (which means that I don't need a real framework like React, Angular or Vue etc.).

**Comment by evanplaice** [comment]
The templating used by lit-html is just a pre-defined tagged template literal. It's worthwhile to learn how tagged templates work, even if you continue to use `lit`.

I'm going to close this issue now. If you'd like to continue discussion and/or would like to contribute, open a new issue under https://github.com/vanillawc/vanillawc.
