### ISSUE TITLE
Instructions for demo

### ISSUE THREAD

**Issue by simonh1000** [vanillawc/wc-monaco-editor#14]
I tried to load the demo page by dragging and dropping index.html into my browser and got 

> Access to script at 'file:///Users/.../wc-monaco-editor-main/index.min.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

I also tried it with a simple dev server and got 

> Failed to load module script: The server responded with a non-JavaScript, CSS MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by evanplaice** [comment]
To run the demo locally use `npm start` from the project root. That'll load `/dev/index.html`.

The files in `/demo` are used to load the online demo via GitHub pages. If you would rather run that locally then run the following from the project root.
```sh
npx live-server --no-browser --port=5500 --open=demo
```
