### ISSUE TITLE
"Unexpected usage"-error when importing from CDN

### ISSUE THREAD

**Issue by gismya** [vanillawc/wc-monaco-editor#15]
When importing from CDN and trying to use the language features, whether by adding a language attribute to the component or programmatically, you get the error message "Unexpected usage" on every keystroke.

[Fiddle](https://jsfiddle.net/w1od3z07/9/)

**Comment by evanplaice** [comment]
If you read the console errors. It's failing to load the worker (ie. Language-Server-Protocol module) directly from the CDN

If you look at the demo linked in `README.md` where it's not loading from a CDN, it works perfectly. This is a problem specific to JSDelivr, not wc-monaco-editor.

I don't think there's a way to fix this component to work directly from a CDN unless the CDN itself natively supports ES modules.
