### ISSUE TITLE
Update to version 0.29

### ISSUE THREAD

**Issue by simonh1000** [vanillawc/wc-monaco-editor#17]
This has an essential fix for many WebComp users in that the ariaContentArea can now be specificied by the developer. this prevents stuff being arbitraily added to the DOM which breaks some language's virtual dom implementations

https://github.com/microsoft/vscode/pull/131865

**Comment by evanplaice** [comment]
Fixed in [v1.10.15](https://github.com/vanillawc/wc-monaco-editor/releases/tag/v1.10.15)

wc-monaco-editor now uses v0.30.1
