### ISSUE TITLE
`editor` is `undefined`

### ISSUE THREAD

**Issue by ypyl** [vanillawc/wc-monaco-editor#18]
Hello, thank you for the great component!

I am trying to use this web component in [Elm](https://elm-lang.org/) and it is working well.
But there is one small issue if I am trying to put property `value` from Elm to the web component.

Sorry, I am not good at developing using web components, so perhaps I am missing something.

I am getting the following call chain when I am trying to set `value` property.
![image](https://user-images.githubusercontent.com/80541559/143780216-1c61157f-b254-41ff-b881-cf5deab790ef.png)

 >I have modified the code in index.js to check `this.editor` for null as it is failing without it.

And it seems that Elm somehow is able to call `value` property before the method `connectedCallback` has been called (so `this.editor` is null).

I am wondering if it is the issue with the web component itself (missing null check) or I am doing something wrong here.
Thank you in advance for your help!

**Comment by evanplaice** [comment]
The issue is with Elm the way it handles external libraries

Specifically, Elm requires special handling to properly register web components in the global scope for usage.

See https://bigardone.dev/blog/2018/09/09/elm-and-web-components

**Comment by ypyl** [comment]
thank you for the help
